version: "3.1"

services:

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  rabbitmq:
    build: ./rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Password1
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: me@myself.com
      PGADMIN_DEFAULT_PASSWORD: Password1
